from __future__ import annotations

from io import BytesIO, StringIO
from typing import List

from docx import Document

from src.services.chart_parser import rows_to_dataframe


def export_chart_csv(rows: List[dict]) -> str:
    dataframe = rows_to_dataframe(rows)
    return dataframe.to_csv(index=False)


def build_version_summary(version_history: List[dict], chart_rows: List[dict]) -> str:
    buffer = StringIO()
    buffer.write("# ClaimCraft AI Claim Chart Refinement Summary\n\n")
    buffer.write(f"Total workflow events: {len(version_history)}\n\n")
    metrics = summarize_version_metrics(version_history, chart_rows)
    buffer.write("## KPI Snapshot\n\n")
    for key, value in metrics.items():
        buffer.write(f"- {key}: {value}\n")
    buffer.write("\n")

    for version in version_history:
        buffer.write(f"## Version {version['version_id']} | {version['decision'].title()}\n")
        buffer.write(f"- Chart Version: v{version.get('chart_version', 1)}\n")
        buffer.write(f"- Timestamp: {version['timestamp']}\n")
        buffer.write(f"- Row ID: {version['row_id']}\n")
        buffer.write(f"- Prompt: {version['user_prompt']}\n")
        buffer.write(f"- Confidence: {version['confidence']}\n")
        buffer.write(
            f"- Scores: evidence={version['scores']['evidence_strength']}, "
            f"reasoning={version['scores']['reasoning_specificity']}, "
            f"relevance={version['scores']['relevance']}\n"
        )
        buffer.write(f"- Summary: {version['summary']}\n")
        buffer.write("- Before Evidence:\n")
        buffer.write(f"{version['old_evidence']}\n")
        buffer.write("- After Evidence:\n")
        buffer.write(f"{version['new_evidence']}\n")
        buffer.write("- Before Reasoning:\n")
        buffer.write(f"{version['old_reasoning']}\n")
        buffer.write("- After Reasoning:\n")
        buffer.write(f"{version['new_reasoning']}\n\n")
        if version.get("scrutiny"):
            scrutiny = version["scrutiny"]
            buffer.write(
                f"- Scrutiny: score={scrutiny.get('scrutiny_score')}, risk={scrutiny.get('risk_level')}, "
                f"citation_coverage={scrutiny.get('citation_coverage')}%\n"
            )
            if scrutiny.get("strengths"):
                buffer.write("- Strengths:\n")
                for item in scrutiny["strengths"]:
                    buffer.write(f"  - {item}\n")
            if scrutiny.get("risks"):
                buffer.write("- Risks:\n")
                for item in scrutiny["risks"]:
                    buffer.write(f"  - {item}\n")
        if version.get("citations"):
            buffer.write("- Citations:\n")
            for citation in version["citations"]:
                buffer.write(
                    f"  - {citation.get('citation_id')} | {citation.get('source_name')}: {citation.get('snippet')}\n"
                )
        if version.get("challenge_questions"):
            buffer.write("- Challenge Questions:\n")
            for question in version["challenge_questions"]:
                buffer.write(f"  - Q: {question.get('question')}\n")
                buffer.write(f"    Why it matters: {question.get('why_it_matters')}\n")
                buffer.write(f"    Prepare: {question.get('how_to_prepare')}\n")
        buffer.write("\n")

    buffer.write("## Final Chart Snapshot\n\n")
    for row in chart_rows:
        buffer.write(f"### Row {row['row_id']}\n")
        buffer.write(f"- Claim Element: {row['claim_element']}\n")
        buffer.write(f"- Evidence: {row['evidence']}\n")
        buffer.write(f"- Reasoning: {row['reasoning']}\n")
        buffer.write(f"- Status: {row['status']}\n\n")
    return buffer.getvalue()


def build_claim_chart_docx(rows: List[dict], title: str = "ClaimCraft Refined Claim Chart") -> bytes:
    document = Document()
    document.add_heading(title, level=1)
    document.add_paragraph("Generated by the ClaimCraft AI claim chart refinement workspace.")

    table = document.add_table(rows=1, cols=4)
    table.style = "Table Grid"
    header_cells = table.rows[0].cells
    header_cells[0].text = "Row ID"
    header_cells[1].text = "Patent Claim Element"
    header_cells[2].text = "Accused Product Feature / Evidence"
    header_cells[3].text = "AI Reasoning"

    for row in rows:
        cells = table.add_row().cells
        cells[0].text = str(row["row_id"])
        cells[1].text = row["claim_element"]
        cells[2].text = row["evidence"]
        cells[3].text = row["reasoning"]

    buffer = BytesIO()
    document.save(buffer)
    buffer.seek(0)
    return buffer.getvalue()


def build_version_summary_docx(
    version_history: List[dict],
    chart_rows: List[dict],
    title: str = "ClaimCraft Version Summary Report",
) -> bytes:
    document = Document()
    document.add_heading(title, level=1)
    document.add_paragraph(f"Total workflow events: {len(version_history)}")
    metrics = summarize_version_metrics(version_history, chart_rows)
    document.add_heading("KPI Snapshot", level=2)
    for key, value in metrics.items():
        document.add_paragraph(f"{key}: {value}")

    if not version_history:
        document.add_paragraph("No changes were recorded during this session.")
    else:
        for version in version_history:
            document.add_heading(
                f"Version {version['version_id']} | Row {version['row_id']} | {version['decision'].title()}",
                level=2,
            )
            document.add_paragraph(f"Chart Version: v{version.get('chart_version', 1)}")
            document.add_paragraph(f"Timestamp: {version['timestamp']}")
            document.add_paragraph(f"Prompt: {version['user_prompt']}")
            document.add_paragraph(f"Confidence: {version['confidence']}")
            document.add_paragraph(
                "Scores: "
                f"evidence={version['scores']['evidence_strength']}, "
                f"reasoning={version['scores']['reasoning_specificity']}, "
                f"relevance={version['scores']['relevance']}"
            )
            document.add_paragraph(f"Summary: {version['summary']}")
            document.add_paragraph(f"Before Evidence: {version['old_evidence']}")
            document.add_paragraph(f"After Evidence: {version['new_evidence']}")
            document.add_paragraph(f"Before Reasoning: {version['old_reasoning']}")
            document.add_paragraph(f"After Reasoning: {version['new_reasoning']}")
            if version.get("scrutiny"):
                scrutiny = version["scrutiny"]
                document.add_paragraph(
                    "Scrutiny: "
                    f"score={scrutiny.get('scrutiny_score')}, "
                    f"risk={scrutiny.get('risk_level')}, "
                    f"citation_coverage={scrutiny.get('citation_coverage')}%"
                )
                for item in scrutiny.get("strengths", []):
                    document.add_paragraph(f"Strength: {item}")
                for item in scrutiny.get("risks", []):
                    document.add_paragraph(f"Risk: {item}")
                for item in scrutiny.get("next_steps", []):
                    document.add_paragraph(f"Next step: {item}")
            if version.get("citations"):
                document.add_paragraph("Citations:")
                for citation in version["citations"]:
                    document.add_paragraph(
                        f"{citation.get('citation_id')} | {citation.get('source_name')} | {citation.get('snippet')}"
                    )
            if version.get("challenge_questions"):
                document.add_paragraph("Challenge Questions:")
                for question in version["challenge_questions"]:
                    document.add_paragraph(f"Q: {question.get('question')}")
                    document.add_paragraph(f"Why it matters: {question.get('why_it_matters')}")
                    document.add_paragraph(f"Preparation: {question.get('how_to_prepare')}")

    document.add_heading("Final Chart Snapshot", level=2)
    for row in chart_rows:
        document.add_heading(f"Row {row['row_id']}", level=3)
        document.add_paragraph(f"Claim Element: {row['claim_element']}")
        document.add_paragraph(f"Evidence: {row['evidence']}")
        document.add_paragraph(f"Reasoning: {row['reasoning']}")
        document.add_paragraph(f"Status: {row['status']}")

    buffer = BytesIO()
    document.save(buffer)
    buffer.seek(0)
    return buffer.getvalue()


def summarize_version_metrics(version_history: List[dict], chart_rows: List[dict]) -> dict:
    latest_metrics = version_history[-1].get("version_metrics") if version_history else {}
    accepted_count = sum(1 for entry in version_history if entry.get("decision") == "accepted")
    risky_rows = sum(1 for row in chart_rows if row.get("weakness_flags"))
    updated_rows = sum(1 for row in chart_rows if row.get("status") == "updated")
    return {
        "Current Version": f"v{version_history[-1]['version_id']}" if version_history else "v1",
        "Accepted Changes": accepted_count,
        "Rows Updated": updated_rows,
        "Rows Still Risky": risky_rows,
        "Evidence Strength Delta": latest_metrics.get("evidence_delta", "n/a"),
        "Reasoning Specificity Delta": latest_metrics.get("reasoning_delta", "n/a"),
        "Citation Coverage Delta": latest_metrics.get("citation_delta", "n/a"),
        "Defensibility Delta": latest_metrics.get("defensibility_delta", "n/a"),
    }
